//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoSoft.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoSoft.Resources.SharedMessages", typeof(SharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty.
        /// </summary>
        public static string Check_CollectionNotEmpty {
            get {
                return ResourceManager.GetString("Check_CollectionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be before 100 years or more than 100.
        /// </summary>
        public static string Check_IsValidDate {
            get {
                return ResourceManager.GetString("Check_IsValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be more than zero.
        /// </summary>
        public static string Check_MoreThanZero {
            get {
                return ResourceManager.GetString("Check_MoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value is not valid.
        /// </summary>
        public static string Check_NotDefault {
            get {
                return ResourceManager.GetString("Check_NotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be empty.
        /// </summary>
        public static string Check_NotEmpty {
            get {
                return ResourceManager.GetString("Check_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be zero.
        /// </summary>
        public static string Check_NotZero {
            get {
                return ResourceManager.GetString("Check_NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be less than zero.
        /// </summary>
        public static string Check_ZeroOrMore {
            get {
                return ResourceManager.GetString("Check_ZeroOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون {0} أكبر من {1} وأصغر من {2}..
        /// </summary>
        public static string InRange {
            get {
                return ResourceManager.GetString("InRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار لغة صحيحة قبل المتابعة..
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد لديك خطأ في إدخال إحدى التواريخ ..
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم صحيح في حقل {0} قبل المتابعة ..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور التي أدخلتها غير صحيحة ..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ قديم في حقل {0} ..
        /// </summary>
        public static string InvalidPastDate {
            get {
                return ResourceManager.GetString("InvalidPastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال توقيت صحيح في حقل {0} قبل المتابعة..
        /// </summary>
        public static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد قمت بإدخال مدى توقيت خاطئ..
        /// </summary>
        public static string InvalidTimeRange {
            get {
                return ResourceManager.GetString("InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال قيمة صحيحة لحقل {0} قبل المتابعة ..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يحتوي {0} على أرقام فقط ..
        /// </summary>
        public static string IsNumeric {
            get {
                return ResourceManager.GetString("IsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال {0} قبل المتابعة ..
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول أو كلمة المرور المدخلة غير صحيحة ..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال أكثر من {0} حرفاً في حقل {1} ..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال قيمة أقل من {0} في حقل {1} ..
        /// </summary>
        public static string MinimumNumber {
            get {
                return ResourceManager.GetString("MinimumNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال أقل من {0} حرفاً أو أكثر من {1} في حقل {2} ..
        /// </summary>
        public static string MinMaxLength {
            get {
                return ResourceManager.GetString("MinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الذي أدخلته موجود مسبقاً ..
        /// </summary>
        public static string NameExisted {
            get {
                return ResourceManager.GetString("NameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        public static string NotExisted {
            get {
                return ResourceManager.GetString("NotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال قيمة صفر في حقل {0} ..
        /// </summary>
        public static string NotZero {
            get {
                return ResourceManager.GetString("NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور التي أدخلتها غير متطابقة ..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ قديم في حقل {0} قبل المتابعة..
        /// </summary>
        public static string PastDateRequired {
            get {
                return ResourceManager.GetString("PastDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد خطأ في الإدخال ..
        /// </summary>
        public static string ResponseState_BadRequest {
            get {
                return ResourceManager.GetString("ResponseState_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد أي نتائج ..
        /// </summary>
        public static string ResponseState_Empty {
            get {
                return ResourceManager.GetString("ResponseState_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست لديك الصلاحية للمتابعة ..
        /// </summary>
        public static string ResponseState_Forbidden {
            get {
                return ResourceManager.GetString("ResponseState_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على أي نتائج ..
        /// </summary>
        public static string ResponseState_NotFound {
            get {
                return ResourceManager.GetString("ResponseState_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه العملية غير مسموحة ..
        /// </summary>
        public static string ResponseState_Unacceptable {
            get {
                return ResourceManager.GetString("ResponseState_Unacceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تسجيل الدخول ..
        /// </summary>
        public static string ResponseState_Unauthorized {
            get {
                return ResourceManager.GetString("ResponseState_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشبكة غير متاحة ..
        /// </summary>
        public static string ResponseState_Unavailable {
            get {
                return ResourceManager.GetString("ResponseState_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملية ناجحة ..
        /// </summary>
        public static string ResponseState_Valid {
            get {
                return ResourceManager.GetString("ResponseState_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال قيمة تحتوي على كسور شاذة في حقل {0} . .
        /// </summary>
        public static string ShouldBeRoundedNumber {
            get {
                return ResourceManager.GetString("ShouldBeRoundedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال عنصر واحد على الأقل في {0} قبل المتابعة ..
        /// </summary>
        public static string ShouldHaveItems {
            get {
                return ResourceManager.GetString("ShouldHaveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار {0} قبل المتابعة ..
        /// </summary>
        public static string ShouldSelected {
            get {
                return ResourceManager.GetString("ShouldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الاختيار من القائمة قبل المتابعة ..
        /// </summary>
        public static string ShouldSelectFromList {
            get {
                return ResourceManager.GetString("ShouldSelectFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح ..
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح ..
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح ..
        /// </summary>
        public static string SuccessEdit {
            get {
                return ResourceManager.GetString("SuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إدخال قيمة أقل من صفر في حقل {0} ..
        /// </summary>
        public static string TrueOrZero {
            get {
                return ResourceManager.GetString("TrueOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم سنة صحيح في حقل {0} ..
        /// </summary>
        public static string TrueYear {
            get {
                return ResourceManager.GetString("TrueYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم الذي أدخلته موجود مسبقا ..
        /// </summary>
        public static string UserExisted {
            get {
                return ResourceManager.GetString("UserExisted", resourceCulture);
            }
        }
    }
}
